apiVersion: ws.cpd.ibm.com/v1beta1
kind: WS
metadata:
  name: {{ .Values.name }}     
  namespace: {{ .Values.cpd_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | default "-3" | quote }}  
spec:
  license:
    accept: true
    license: Enterprise   
  version: {{ .Values.spec.version }}   
  storageVendor: {{ .Values.spec.storageVendor }}  
  storageClass: {{ .Values.spec.storageClass }}   