apiVersion: ws.cpd.ibm.com/v1beta1
kind: WS
metadata:
  name: {{ .Values.name }}     
  namespace: {{ .Values.cpd_namespace }}
spec:
  license:
    accept: {{ .Values.spec.license.accept }}
    license: {{ .Values.spec.license.license }}     
  version: {{ .Values.spec.version }}   
  storageVendor: {{ .Values.spec.storageVendor }}  
  storageClass: {{ .Values.spec.storageClass }}   