apiVersion: ws.cpd.ibm.com/v1beta1
kind: WS
metadata:
  name: {{ .Values.name }}     
  namespace: {{ .Values.cpd_namespace }}
spec:
  license:
    accept: true
    license: Enterprise     
  version: {{ .Values.version }}   
  storageVendor: {{ .Values.storageVendor }}  
  storageClass: {{ .Values.storageClass }}   