apiVersion: ws.cpd.ibm.com/v1beta1
kind: WS
metadata:
  name: ws-cr     
  namespace: gitops-cp4d-instance     
spec:
  license:
    accept: true
    license: Enterprise     
  version: 4.0.5
  storageVendor: portworx
  storageClass: portworx-shared-gp3 