apiVersion: ws.cpd.ibm.com/v1beta1
kind: WS
metadata:
  name: ws-cr     # This is the recommended name, but you can change it
  namespace: gitops-cp4d-instance     # Replace with the project where you will install Watson Studio
spec:
  license:
    accept: true
    license: Enterprise     # Specify the license you purchased
  version: 4.0.5
  storageVendor: portworx
  storageClass: portworx-shared-gp3 