# Default values for Watston Studio Instance Cr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: ws-cr
cpd_namespace: gitops-cp4d-instance
spec:
  license:
    accept: true
    license: Enterprise
  version: 4.0.5
  storageVendor: portworx
  storageClass: portworx-shared-gp3